version: '3'
services:
  nginx:
    image: library/nginx:1.19
    container_name: ngix
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/pi/DockerVol/certbot/key/:/etc/letsencrypt/live/manciotech.fun/
      - /home/pi/DockerVol/certbot/conf/:/etc/letsencrypt/
      - /home/pi/DockerVol/certbot/www/:/var/www/certbot/
      - /home/pi/DockerVol/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  frontend:
    image: mancioman2/manciotechweb:latest
    container_name: frontend
    ports:
      - 3001:80
#  certbot:
#    image: mancioman2/mycertbot:latest
#    container_name: certbot
#    volumes:
#      - /home/pi/DockerVol/certbot/key/:/etc/letsencrypt/live/manciotech.fun/
#      - /home/pi/DockerVol/certbot/conf/:/etc/letsencrypt/
#      - /home/pi/DockerVol/certbot/www/:/var/www/certbot/
#    command: >
#      bash -c "sleep 20s
#      && echo 'hey it fail? Did you restart your server? (pagekite, ecc....)'
#      && certbot certonly --webroot -w /var/www/certbot/ -d manciotech.fun -d www.manciotech.fun --renew-by-default --agree-tos"